project_name: falkordb-cli

before:
  hooks:
    # Ensure targets are available and build each platform binary with cargo
    - rustup target add x86_64-unknown-linux-musl || true
    - rustup target add x86_64-pc-windows-msvc || true
    - rustup target add x86_64-apple-darwin || true
    - cargo build --release --target x86_64-unknown-linux-gnu || true
    - cargo build --release --target x86_64-unknown-linux-musl || true
    - cargo build --release --target x86_64-pc-windows-msvc || true
    - cargo build --release --target x86_64-apple-darwin || true

archives:
  - id: unix
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "target/*/release/falkordb-cli"
    format: tar.gz

  - id: windows
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "target/*/release/falkordb-cli.exe"
    format: zip

release:
  github:
    owner: FalkorDB
    name: falkordb-cli

checksum:
  name_template: "COMBINED_SHA256SUMS.txt"

signs: []

changelog:
  use: github
